import Providers from "./providers/providers";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {

  return (
    <html lang="en" className="w-full">

      <body className="w-full">

        <Providers>
          Hello
        </Providers>

      </body>

    </html>
  )
}
