
//Theme Povider ...
import Providers from "./providers/providers";

//MUI Components
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import AppBar from '@mui/material/AppBar';
import Grid from '@mui/material/Unstable_Grid2';

import NavPanel from './components/Layout/NavPanel'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {

  return (
    <html>

      <body>
        <Providers>
          <Grid container spacing={0}>
            
            <Grid xs sx={{height:'100vh', borderRight: '1px solid #333'}}>
              <NavPanel />
            </Grid>

            <Grid xs={10.5} sx={{height: '100vh'}} >
              <Box sx={{height: '100%',width:'100%'}}>

                <Box sx={{height:'6%',zIndex:'9999'}}>
                  <Toolbar disableGutters variant='dense' sx={{borderBottom:'1px solid #333',height:'100%'}}>
                    TopBar
                  </Toolbar>
                </Box>

                <Box sx={{height: '94%',overflowY: 'scroll'}}>
                  <Box sx={{height:'1500px'}}>
                    {children}
                  </Box>
                </Box>

              </Box>
            </Grid>  
            
          </Grid>
        </Providers>
      </body>

    </html>
  )
}
